# Generated by Django 3.2.25 on 2024-06-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_brand_account_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_account',
            old_name='seller_id',
            new_name='author',
        ),
    ]
