# Generated by Django 3.2.25 on 2024-06-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_seller_id_brand_account_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_account',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
