# Generated by Django 3.2.25 on 2024-06-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
