# Generated by Django 3.2.25 on 2024-06-29 18:03

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20240629_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_account',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default='path/to/default/image.jpg', null=True, upload_to=''),
        ),
    ]
